---
title: "Visiualizations Work Sheet"
author: "Martin Gleason, MS"
date: "8/13/2018"
output: html_document
---
```{r, packages_and_source, include= TRUE, echo = FALSE, warnings = FALSE, message = FALSE}
source("mock_etl.R")
library(kableExtra)
```

#Sample Visualizations for Demographics
```{r, charts, include = TRUE, echo=FALSE, warnings = FALSE, message = FALSE}
kable(demographics) %>% 
  kable_styling(bootstrap_options = c("striped", "bordered", "hover", "responsive"))

demo_ZRG <- demographics %>% group_by(`Client Zipcode`, `Client Race`, `Client Gender`) %>%
  summarize(Totals = n())

demo_ZRG %>% kable() %>%
  kable_styling(bootstrap_options = c("striped", "bordered", "hover", "responsive"))

demographics %>% ggplot(aes(x = as.factor(`Client Zipcode`), fill = `Client Race`)) +
  geom_histogram(stat = "count", position = "dodge") +
  facet_grid(~ `Client Gender`) +
  labs(x = "Client Zipcode", y = "Total Per Zipcode", title = "JRA: Clients by Zipcode, Gender, and Race") +
  coord_flip()
  #theme(axis.text.x = element_text(angle = 90))

```

# Client Scores

* Mike, please correct me but, I think the SQL tables will be something like:
  + Demograhics: ClientID, Client First Name, Client Last Name, Client Zipcode[^1], Client Race, Client Gender
  + JRA Scores: Client_ID, Reassessment, Scores per Domain
```{r, client_scores, include = TRUE, echo = FALSE, warnings = FALSE, message = FALSE}
client_scores %>% 
  ggplot(aes(x = as.factor(`Client ID`), y= Score)) + geom_point() +
  labs(x = "Client ID", title = "Client Risk Score", y = "JRA Score")
```

[^1]: Actually address, but, for the demo purpose, we're just going to stick to Zip.